### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stormbeforesunsetbee** [rivanfebrian123/Litesy#1]
- [ ]  Standardise our libraries name, take inspirations from [Valadoc](https://valadoc.org/index.htm) or [PyGObjec](https://lazka.github.io/pgi-docs/)t API Reference.
- [ ] Create a database of matching API package bundle in some distributions and open source libraries repository, such as [AARNet](https://mirror.aarnet.edu.au/) for Linux and Unix's, [Homebrew Formulae](https://formulae.brew.sh/formula/) for macOS, and [MSYS2](http://repo.msys2.org/) for Windows. This supposed to simplify describing which of packages needed by your app.
- [ ] Check for bindings of the library reability, I meant sometime there's such language bindings that doesn't give a complete features like in the originals. E.g. GtkTemplate feature in GtkSharp.
- [ ] Sometime, when we will build an app with the latest library, but your distribution repository doesn't provide them, we've to build them ourselves. So, we've to host our own libraries repository to solve this problem. Also, sometime pkg-config doesn't satisfy us, e.g when we're looking for `gstreamer-player-1.0` in Fedora, it's give us: 
```
No match for argument: pkg-config(gstreamer-player-1.0)
Error: Unable to find a match
```
So, we've to find it manually in [rpmfind](https://rpmfind.net/linux/rpm2html/search.php?query=pkgconfig(gstreamer-player-1.0)) or something else.
And sometime there will distribution package management we don't expect, e.g. [llvm-config](https://bugzilla.redhat.com/show_bug.cgi?id=855882) that moved to llvm-devel package.

- [ ] Wait for another to-do. Insha Allah.
